### PR TITLE
Refactor Makefile to push to Dockerhub

### PR DESCRIPTION
**Pull request by eganjs**
* Improve encapsulation by bringing more of the CI/CD into the Makefile
* Maintain minimal dependency on Azure Pipelines by using it as an
orchestrator
* Reduce dependency on Dockerhub by favouring push over pull for images

### CODE REVIEW

**Comment by elduddz** [comment]
Is it bad to have a dependancy on docker hub?

**Comment by JoelClemence** [comment]
Also, Azure Pipelines can push to Docker hub too. Depending on how strongly @elduddz feels this could be another way to acheive this.

**Comment by eganjs** [comment]
> Is it bad to have a dependancy on docker hub?

Could you elaborate on this?

**Comment by eganjs** [comment]
> Also, Azure Pipelines can push to Docker hub too. Depending on how strongly @elduddz feels this could be another way to acheive this.

This is what `make push` does, it runs `docker push`. The target repository is configurable through a hard coded value in the Makefile, so if necessary we can change where they are being pushed.

**Comment by elduddz** [comment]
> > Is it bad to have a dependancy on docker hub?
> 
> Could you elaborate on this?

Reduce dependency on Dockerhub by favouring push over pull for images
^
was commenting on this statement.

**Comment by elduddz** [comment]
> > Also, Azure Pipelines can push to Docker hub too. Depending on how strongly @elduddz feels this could be another way to acheive this.
> 
> This is what `make push` does, it runs `docker push`. The target repository is configurable through a hard coded value in the Makefile, so if necessary we can change where they are being pushed.

and it runs all images for 1 change? I guess I just want to understand the mechanics of when a change occurs.

**Pull request merged**
